name: UUID v5 Action
description: Generate UUID v5 values
inputs:
  value:
    description: The value to convert into a UUID
    required: false

  namespace:
    description: The UUID namespace value
    required: true

outputs:
  uuid:
    description: The UUID v5 value

  uuid_short:
    description: The UUID v5 value stripped of any dashes so that it is 32 characters long

  namespace_uuid:
    description: The UUID value used for the namespace (converts any string value supplied for the namespace into a valid UUID)

runs:
  using: node20
  main: dist/index.js